package com.oo.projpedidoprodutos.gui.dialogs;

import com.oo.projpedidoprodutos.classes.Pedido;
import com.oo.projpedidoprodutos.classes.Pessoa;
import com.oo.projpedidoprodutos.gerenciador.GerenciadorPessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class DlgEscolhaCliente extends javax.swing.JDialog {

    private Pedido pedido;
    public Pessoa pessoaEscolhida;
    private GerenciadorPessoa gerentePessoas;

    public DlgEscolhaCliente(java.awt.Frame parent, boolean modal, Pedido pedido) {

        super(parent, modal);
        initComponents();
        this.pessoaEscolhida = new Pessoa();
        this.pedido = pedido;

        this.gerentePessoas = new GerenciadorPessoa();
        this.gerentePessoas.carregarDoArquivo("ListagemPessoas.csv");
        String listagem = this.gerentePessoas.toString();
        edtListagem.setText(listagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        splConteudo = new javax.swing.JSplitPane();
        panListaPessoas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNome2 = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();
        panEscolhido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblPessoaEscolhida = new javax.swing.JTextArea();
        btnAddPessoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha uma pessoa");

        splConteudo.setDividerLocation(420);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lblNome2.setText("CPF:");
        jPanel1.add(lblNome2);
        jPanel1.add(edtCpf);

        btnPesquisar.setForeground(new java.awt.Color(0, 25, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnPesquisar.setText("Buscar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar);

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout panListaPessoasLayout = new javax.swing.GroupLayout(panListaPessoas);
        panListaPessoas.setLayout(panListaPessoasLayout);
        panListaPessoasLayout.setHorizontalGroup(
            panListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaPessoasLayout.createSequentialGroup()
                .addGroup(panListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panListaPessoasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panListaPessoasLayout.setVerticalGroup(
            panListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaPessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        splConteudo.setLeftComponent(panListaPessoas);

        lblPessoaEscolhida.setEditable(false);
        lblPessoaEscolhida.setColumns(20);
        lblPessoaEscolhida.setRows(5);
        lblPessoaEscolhida.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas Escolhida"));
        jScrollPane2.setViewportView(lblPessoaEscolhida);

        btnAddPessoa.setBackground(new java.awt.Color(0, 153, 51));
        btnAddPessoa.setText("Add Pessoa");
        btnAddPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEscolhidoLayout = new javax.swing.GroupLayout(panEscolhido);
        panEscolhido.setLayout(panEscolhidoLayout);
        panEscolhidoLayout.setHorizontalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnAddPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panEscolhidoLayout.setVerticalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAddPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        splConteudo.setRightComponent(panEscolhido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(splConteudo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(splConteudo)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        String cpfEscolhido = edtCpf.getText();
        if (!cpfEscolhido.isEmpty()) {
            pessoaEscolhida = this.gerentePessoas.buscarPessoa(cpfEscolhido);

            if (pessoaEscolhida == null) {
                JOptionPane.showMessageDialog(this, "Não existe este CPF.");
                lblPessoaEscolhida.setText("");
            } else {
                lblPessoaEscolhida.setText(pessoaEscolhida.toString());
            }
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAddPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPessoaActionPerformed
        if (pessoaEscolhida == null) {
            int response = JOptionPane.showConfirmDialog(null,
                    "Nenhum cliente foi escolhido. Deseja continuar?",
                    "Confirm",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                dispose();
            }
        } else {
            this.pedido.setCliente(pessoaEscolhida);
            dispose();
        }
    }//GEN-LAST:event_btnAddPessoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPessoa;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JTextArea lblPessoaEscolhida;
    private javax.swing.JPanel panEscolhido;
    private javax.swing.JPanel panListaPessoas;
    private javax.swing.JSplitPane splConteudo;
    // End of variables declaration//GEN-END:variables
}
